services:
  finance-tracker-ui:
    container_name: finance-tracker-ui
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
